### ISSUE TITLE
Wrong size for sigCSA_cry_11!

### ISSUE THREAD

**Issue by akm1374** [gagan405/WallTree#1]
Hi,

while generating the multiplier for input length of 16, the sigCSA_cry_11 length is (24 downto 0), however, it should be (30 downto 0).

Look at line: 83

Thanks.

[WallTree.tar.gz](https://github.com/gagan405/WallTree/files/5534276/WallTree.tar.gz)

**Comment by gagan405** [comment]
I am not maintaining this anymore. If you think there is a bug, feel free to fork and correct it.
